export default {
  weekday:{
    zh:{
      '0':'星期日',
      '1':'星期一',
      '2':'星期二',
      '3':'星期三',
      '4':'星期四',
      '5':'星期五',
      '6':'星期六'
    },
    en:{
      '0':'Sunday',
      '1':'Monday',
      '2':'Tuesday',
      '3':'Wednesday',
      '4':'Thursday',
      '5':'Friday',
      '6':'Saturday'
    }
  },
  month:{
    zh:{
      '01':'一月',
      '02':'二月',
      '03':'三月',
      '04':'四月',
      '05':'五月',
      '06':'六月',
      '07':'七月',
      '08':'八月',
      '09':'九月',
      '10':'十月',
      '11':'十一月',
      '12':'十二月',
    },
    en:{
      '01':'January',
      '02':'Febuary',
      '03':'March',
      '04':'April',
      '05':'May',
      '06':'June',
      '07':'July',
      '08':'August',
      '09':'September',
      '10':'October',
      '11':'November',
      '12':'December',
    },
  }

}